# Generated by Django 5.2.8 on 2026-02-09 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prolean', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Téléphone'),
        ),
    ]
